<?php
    require_once 'conn.php';
    require_once 'methods.php';
    require_once 'charge.php';

	class ThroatSwabCS {

        // create a throat_swab_cs record
        public static function create_throat_swab_cs($patient_id, $culture, $bacteria_one, $bacteria_two, $bacteria_three, $antibiotics_one, $antibiotics_two, $antibiotics_three, $antibiotics_four, $antibiotics_five, $antibiotics_six, $antibiotics_seven, $antibiotics_eight, $antibiotics_nine, $antibiotics_ten, $antibiotics_eleven, $antibiotics_twelve, $antibiotics_thirteen, $antibiotics_fourteen, $antibiotics_fifteen, $antibiotics_sixteen, $antibiotics_seventeen, $antibiotics_eighteen, $antibiotics_nineteen, $antibiotics_twenty, $antibiotics_twenty_one, $antibiotics_twenty_two, $antibiotics_twenty_three, $antibiotics_twenty_four, $sensitivity_one, $sensitivity_two, $sensitivity_three, $sensitivity_four, $sensitivity_five, $sensitivity_six, $sensitivity_seven, $sensitivity_eight, $sensitivity_nine, $sensitivity_ten, $sensitivity_eleven, $sensitivity_twelve, $sensitivity_thirteen, $sensitivity_fourteen, $sensitivity_fifteen, $sensitivity_sixteen, $sensitivity_seventeen, $sensitivity_eighteen, $sensitivity_nineteen, $sensitivity_twenty, $sensitivity_twenty_one, $sensitivity_twenty_two, $sensitivity_twenty_three, $sensitivity_twenty_four, $comments, $added_by, $conn){
            $invoice_id               = Methods::get_invoice_id('Throat Swab C/S', $conn);
            $amount                   = Charge::read_charge('76', $conn);
            $culture                  = is_array($culture) ? implode(', ', $culture) : $culture;
            $bacteria_one             = is_array($bacteria_one) ? implode(', ', $bacteria_one) : $bacteria_one;
            $bacteria_two             = is_array($bacteria_two) ? implode(', ', $bacteria_two) : $bacteria_two;
            $bacteria_three           = is_array($bacteria_three) ? implode(', ', $bacteria_three) : $bacteria_three;
            $antibiotics_one          = is_array($antibiotics_one) ? implode(', ', $antibiotics_one) : $antibiotics_one;
            $antibiotics_two          = is_array($antibiotics_two) ? implode(', ', $antibiotics_two) : $antibiotics_two;
            $antibiotics_three        = is_array($antibiotics_three) ? implode(', ', $antibiotics_three) : $antibiotics_three;
            $antibiotics_four         = is_array($antibiotics_four) ? implode(', ', $antibiotics_four) : $antibiotics_four;
            $antibiotics_five         = is_array($antibiotics_five) ? implode(', ', $antibiotics_five) : $antibiotics_five;
            $antibiotics_six          = is_array($antibiotics_six) ? implode(', ', $antibiotics_six) : $antibiotics_six;
            $antibiotics_seven        = is_array($antibiotics_seven) ? implode(', ', $antibiotics_seven) : $antibiotics_seven;
            $antibiotics_eight        = is_array($antibiotics_eight) ? implode(', ', $antibiotics_eight) : $antibiotics_eight;
            $antibiotics_nine         = is_array($antibiotics_nine) ? implode(', ', $antibiotics_nine) : $antibiotics_nine;
            $antibiotics_ten          = is_array($antibiotics_ten) ? implode(', ', $antibiotics_ten) : $antibiotics_ten;
            $antibiotics_eleven       = is_array($antibiotics_eleven) ? implode(', ', $antibiotics_eleven) : $antibiotics_eleven;
            $antibiotics_twelve       = is_array($antibiotics_twelve) ? implode(', ', $antibiotics_twelve) : $antibiotics_twelve;
            $antibiotics_thirteen     = is_array($antibiotics_thirteen) ? implode(', ', $antibiotics_thirteen) : $antibiotics_thirteen;
            $antibiotics_fourteen     = is_array($antibiotics_fourteen) ? implode(', ', $antibiotics_fourteen) : $antibiotics_fourteen;
            $antibiotics_fifteen      = is_array($antibiotics_fifteen) ? implode(', ', $antibiotics_fifteen) : $antibiotics_fifteen;
            $antibiotics_sixteen      = is_array($antibiotics_sixteen) ? implode(', ', $antibiotics_sixteen) : $antibiotics_sixteen;
            $antibiotics_seven        = is_array($antibiotics_seven) ? implode(', ', $antibiotics_seven) : $antibiotics_seven;
            $antibiotics_eighteen     = is_array($antibiotics_eighteen) ? implode(', ', $antibiotics_eighteen) : $antibiotics_eighteen;
            $antibiotics_nineteen     = is_array($antibiotics_nineteen) ? implode(', ', $antibiotics_nineteen) : $antibiotics_nineteen;
            $antibiotics_twenty       = is_array($antibiotics_twenty) ? implode(', ', $antibiotics_twenty) : $antibiotics_twenty;
            $antibiotics_twenty_one   = is_array($antibiotics_twenty_one) ? implode(', ', $antibiotics_twenty_one) : $antibiotics_twenty_one;
            $antibiotics_twenty_two   = is_array($antibiotics_twenty_two) ? implode(', ', $antibiotics_twenty_two) : $antibiotics_twenty_two;
            $antibiotics_twenty_three = is_array($antibiotics_twenty_three) ? implode(', ', $antibiotics_twenty_three) : $antibiotics_twenty_three;
            $antibiotics_twenty_four  = is_array($antibiotics_twenty_four) ? implode(', ', $antibiotics_twenty_four) : $antibiotics_twenty_four;
            
            try{
                $query = $conn->prepare('INSERT INTO throat_swab_cs(invoice_id, patient_id, culture, bacteria_one, bacteria_two, bacteria_three, antibiotics_one, antibiotics_two, antibiotics_three, antibiotics_four, antibiotics_five, antibiotics_six, antibiotics_seven, antibiotics_eight, antibiotics_nine, antibiotics_ten, antibiotics_eleven, antibiotics_twelve, antibiotics_thirteen, antibiotics_fourteen, antibiotics_fifteen, antibiotics_sixteen, antibiotics_seventeen, antibiotics_eighteen, antibiotics_nineteen, antibiotics_twenty, antibiotics_twenty_one, antibiotics_twenty_two, antibiotics_twenty_three, antibiotics_twenty_four, sensitivity_one, sensitivity_two, sensitivity_three, sensitivity_four, sensitivity_five, sensitivity_six, sensitivity_seven, sensitivity_eight, sensitivity_nine, sensitivity_ten, sensitivity_eleven, sensitivity_twelve, sensitivity_thirteen, sensitivity_fourteen, sensitivity_fifteen, sensitivity_sixteen, sensitivity_seventeen, sensitivity_eighteen, sensitivity_nineteen, sensitivity_twenty, sensitivity_twenty_one, sensitivity_twenty_two, sensitivity_twenty_three, sensitivity_twenty_four, comments, added_by)  VALUES(:invoice_id, :patient_id, :culture, :bacteria_one, :bacteria_two, :bacteria_three, :antibiotics_one, :antibiotics_two, :antibiotics_three, :antibiotics_four, :antibiotics_five, :antibiotics_six, :antibiotics_seven, :antibiotics_eight, :antibiotics_nine, :antibiotics_ten, :antibiotics_eleven, :antibiotics_twelve, :antibiotics_thirteen, :antibiotics_fourteen, :antibiotics_fifteen, :antibiotics_sixteen, :antibiotics_seventeen, :antibiotics_eighteen, :antibiotics_nineteen, :antibiotics_twenty, :antibiotics_twenty_one, :antibiotics_twenty_two, :antibiotics_twenty_three, :antibiotics_twenty_four, :sensitivity_one, :sensitivity_two, :sensitivity_three, :sensitivity_four, :sensitivity_five, :sensitivity_six, :sensitivity_seven, :sensitivity_eight, :sensitivity_nine, :sensitivity_ten, :sensitivity_eleven, :sensitivity_twelve, :sensitivity_thirteen, :sensitivity_fourteen, :sensitivity_fifteen, :sensitivity_sixteen, :sensitivity_seventeen, :sensitivity_eighteen, :sensitivity_nineteen, :sensitivity_twenty, :sensitivity_twenty_one, :sensitivity_twenty_two, :sensitivity_twenty_three, :sensitivity_twenty_four, :comments, :added_by)');
                $query->execute([':invoice_id' => $invoice_id, ':patient_id' => $patient_id, ':culture' => $culture, ':bacteria_one' => $bacteria_one, ':bacteria_two' => $bacteria_two, ':bacteria_three' => $bacteria_three, ':antibiotics_one' => $antibiotics_one, ':antibiotics_two' => $antibiotics_two, ':antibiotics_three' => $antibiotics_three, ':antibiotics_four' => $antibiotics_four, ':antibiotics_five' => $antibiotics_five, ':antibiotics_six' => $antibiotics_six, ':antibiotics_seven' => $antibiotics_seven, ':antibiotics_eight' => $antibiotics_eight, ':antibiotics_nine' => $antibiotics_nine, ':antibiotics_ten' => $antibiotics_ten, ':antibiotics_eleven' => $antibiotics_eleven, ':antibiotics_twelve' => $antibiotics_twelve, ':antibiotics_thirteen' => $antibiotics_thirteen, ':antibiotics_fourteen' => $antibiotics_fourteen, ':antibiotics_fifteen' => $antibiotics_fifteen, ':antibiotics_sixteen' => $antibiotics_sixteen, ':antibiotics_seventeen' => $antibiotics_seventeen, ':antibiotics_eighteen' => $antibiotics_eighteen, ':antibiotics_nineteen' => $antibiotics_nineteen, ':antibiotics_twenty' => $antibiotics_twenty, ':antibiotics_twenty_one' => $antibiotics_twenty_one, ':antibiotics_twenty_two' => $antibiotics_twenty_two, ':antibiotics_twenty_three' => $antibiotics_twenty_three, ':antibiotics_twenty_four' => $antibiotics_twenty_four, ':sensitivity_one' => $sensitivity_one, ':sensitivity_two' => $sensitivity_two, ':sensitivity_three' => $sensitivity_three, ':sensitivity_four' => $sensitivity_four, ':sensitivity_five' => $sensitivity_five, ':sensitivity_six' => $sensitivity_six, ':sensitivity_seven' => $sensitivity_seven, ':sensitivity_eight' => $sensitivity_eight, ':sensitivity_nine' => $sensitivity_nine, ':sensitivity_ten' => $sensitivity_ten, ':sensitivity_eleven' => $sensitivity_eleven, ':sensitivity_twelve' => $sensitivity_twelve, ':sensitivity_thirteen' => $sensitivity_thirteen, ':sensitivity_fourteen' => $sensitivity_fourteen, ':sensitivity_fifteen' => $sensitivity_fifteen, ':sensitivity_sixteen' => $sensitivity_sixteen, ':sensitivity_seventeen' => $sensitivity_seventeen, ':sensitivity_eighteen' => $sensitivity_eighteen, ':sensitivity_nineteen' => $sensitivity_nineteen, ':sensitivity_twenty' => $sensitivity_twenty, ':sensitivity_twenty_one' => $sensitivity_twenty_one, ':sensitivity_twenty_two' => $sensitivity_twenty_two, ':sensitivity_twenty_three' => $sensitivity_twenty_three, ':sensitivity_twenty_four' => $sensitivity_twenty_four, ':comments' => $comments, ':added_by' => $added_by]);

                return true;
            }catch(PDOException $ex){
            	return false;
            }
        }

        // fetch all throat_swab_cs records
        public static function read_throat_swab_cs($conn){
            try{
                $query = $conn->prepare('SELECT ts.id, ts.invoice_id, ts.patient_id, ts.culture, ts.bacteria_one, ts.bacteria_two, ts.bacteria_three, ts.antibiotics_one, ts.antibiotics_two, ts.antibiotics_three, ts.antibiotics_four, ts.antibiotics_five, ts.antibiotics_six, ts.antibiotics_seven, ts.antibiotics_eight, ts.antibiotics_nine, ts.antibiotics_ten, ts.antibiotics_eleven, ts.antibiotics_twelve, ts.antibiotics_thirteen, ts.antibiotics_fourteen, ts.antibiotics_fifteen, ts.antibiotics_sixteen, ts.antibiotics_seventeen, ts.antibiotics_eighteen, ts.antibiotics_nineteen, ts.antibiotics_twenty, ts.antibiotics_twenty_one, ts.antibiotics_twenty_two, ts.antibiotics_twenty_three, ts.antibiotics_twenty_four, ts.sensitivity_one, ts.sensitivity_two, ts.sensitivity_three, ts.sensitivity_four, ts.sensitivity_five, ts.sensitivity_six, ts.sensitivity_seven, ts.sensitivity_eight, ts.sensitivity_nine, ts.sensitivity_ten, ts.sensitivity_eleven, ts.sensitivity_twelve, ts.sensitivity_thirteen, ts.sensitivity_fourteen, ts.sensitivity_fifteen, ts.sensitivity_sixteen, ts.sensitivity_seventeen, ts.sensitivity_eighteen, ts.sensitivity_nineteen, ts.sensitivity_twenty, ts.sensitivity_twenty_one, ts.sensitivity_twenty_two, ts.sensitivity_twenty_three, ts.sensitivity_twenty_four, ts.comments, ts.added_by, ts.date_added, p.date_of_birth, p.gender, p.first_name as pfirst_name, p.middle_name as pmiddle_name, p.last_name as plast_name, u.first_name as ufirst_name, u.other_name as uother_name, u.last_name as ulast_name FROM throat_swab_cs ts INNER JOIN patients p ON ts.patient_id = p.patient_id INNER JOIN users u ON ts.added_by = u.staff_id');
                $query->execute();

                return $query->fetchAll(PDO::FETCH_OBJ);
            }catch(PDOException $ex){}
        }

        // fetch a throat_swab_cs record
        public static function read_a_throat_swab_cs($id, $conn){
            try{
                $query = $conn->prepare('SELECT ts.id, ts.invoice_id, ts.patient_id, ts.culture, ts.bacteria_one, ts.bacteria_two, ts.bacteria_three, ts.antibiotics_one, ts.antibiotics_two, ts.antibiotics_three, ts.antibiotics_four, ts.antibiotics_five, ts.antibiotics_six, ts.antibiotics_seven, ts.antibiotics_eight, ts.antibiotics_nine, ts.antibiotics_ten, ts.antibiotics_eleven, ts.antibiotics_twelve, ts.antibiotics_thirteen, ts.antibiotics_fourteen, ts.antibiotics_fifteen, ts.antibiotics_sixteen, ts.antibiotics_seventeen, ts.antibiotics_eighteen, ts.antibiotics_nineteen, ts.antibiotics_twenty, ts.antibiotics_twenty_one, ts.antibiotics_twenty_two, ts.antibiotics_twenty_three, ts.antibiotics_twenty_four, ts.sensitivity_one, ts.sensitivity_two, ts.sensitivity_three, ts.sensitivity_four, ts.sensitivity_five, ts.sensitivity_six, ts.sensitivity_seven, ts.sensitivity_eight, ts.sensitivity_nine, ts.sensitivity_ten, ts.sensitivity_eleven, ts.sensitivity_twelve, ts.sensitivity_thirteen, ts.sensitivity_fourteen, ts.sensitivity_fifteen, ts.sensitivity_sixteen, ts.sensitivity_seventeen, ts.sensitivity_eighteen, ts.sensitivity_nineteen, ts.sensitivity_twenty, ts.sensitivity_twenty_one, ts.sensitivity_twenty_two, ts.sensitivity_twenty_three, ts.sensitivity_twenty_four, ts.comments, ts.added_by, ts.date_added, p.date_of_birth, p.gender, p.first_name as pfirst_name, p.middle_name as pmiddle_name, p.last_name as plast_name, u.first_name as ufirst_name, u.other_name as uother_name, u.last_name as ulast_name FROM throat_swab_cs ts INNER JOIN patients p ON ts.patient_id = p.patient_id INNER JOIN users u ON ts.added_by = u.staff_id WHERE ts.id = :id');
                $query->execute([':id' => $id]);

                return $query->fetch(PDO::FETCH_OBJ);
            }catch(PDOException $ex){}
        }

        // update a throat_swab_cs record
        public static function update_throat_swab_cs($id, $patient_id, $culture, $bacteria_one, $bacteria_two, $bacteria_three, $antibiotics_one, $antibiotics_two, $antibiotics_three, $antibiotics_four, $antibiotics_five, $antibiotics_six, $antibiotics_seven, $antibiotics_eight, $antibiotics_nine, $antibiotics_ten, $antibiotics_eleven, $antibiotics_twelve, $antibiotics_thirteen, $antibiotics_fourteen, $antibiotics_fifteen, $antibiotics_sixteen, $antibiotics_seventeen, $antibiotics_eighteen, $antibiotics_nineteen, $antibiotics_twenty, $antibiotics_twenty_one, $antibiotics_twenty_two, $antibiotics_twenty_three, $antibiotics_twenty_four, $sensitivity_one, $sensitivity_two, $sensitivity_three, $sensitivity_four, $sensitivity_five, $sensitivity_six, $sensitivity_seven, $sensitivity_eight, $sensitivity_nine, $sensitivity_ten, $sensitivity_eleven, $sensitivity_twelve, $sensitivity_thirteen, $sensitivity_fourteen, $sensitivity_fifteen, $sensitivity_sixteen, $sensitivity_seventeen, $sensitivity_eighteen, $sensitivity_nineteen, $sensitivity_twenty, $sensitivity_twenty_one, $sensitivity_twenty_two, $sensitivity_twenty_three, $sensitivity_twenty_four, $comments, $conn) {
            $culture                  = is_array($culture) ? implode(', ', $culture) : $culture;
            $bacteria_one             = is_array($bacteria_one) ? implode(', ', $bacteria_one) : $bacteria_one;
            $bacteria_two             = is_array($bacteria_two) ? implode(', ', $bacteria_two) : $bacteria_two;
            $bacteria_three           = is_array($bacteria_three) ? implode(', ', $bacteria_three) : $bacteria_three;
            $antibiotics_one          = is_array($antibiotics_one) ? implode(', ', $antibiotics_one) : $antibiotics_one;
            $antibiotics_two          = is_array($antibiotics_two) ? implode(', ', $antibiotics_two) : $antibiotics_two;
            $antibiotics_three        = is_array($antibiotics_three) ? implode(', ', $antibiotics_three) : $antibiotics_three;
            $antibiotics_four         = is_array($antibiotics_four) ? implode(', ', $antibiotics_four) : $antibiotics_four;
            $antibiotics_five         = is_array($antibiotics_five) ? implode(', ', $antibiotics_five) : $antibiotics_five;
            $antibiotics_six          = is_array($antibiotics_six) ? implode(', ', $antibiotics_six) : $antibiotics_six;
            $antibiotics_seven        = is_array($antibiotics_seven) ? implode(', ', $antibiotics_seven) : $antibiotics_seven;
            $antibiotics_eight        = is_array($antibiotics_eight) ? implode(', ', $antibiotics_eight) : $antibiotics_eight;
            $antibiotics_nine         = is_array($antibiotics_nine) ? implode(', ', $antibiotics_nine) : $antibiotics_nine;
            $antibiotics_ten          = is_array($antibiotics_ten) ? implode(', ', $antibiotics_ten) : $antibiotics_ten;
            $antibiotics_eleven       = is_array($antibiotics_eleven) ? implode(', ', $antibiotics_eleven) : $antibiotics_eleven;
            $antibiotics_twelve       = is_array($antibiotics_twelve) ? implode(', ', $antibiotics_twelve) : $antibiotics_twelve;
            $antibiotics_thirteen     = is_array($antibiotics_thirteen) ? implode(', ', $antibiotics_thirteen) : $antibiotics_thirteen;
            $antibiotics_fourteen     = is_array($antibiotics_fourteen) ? implode(', ', $antibiotics_fourteen) : $antibiotics_fourteen;
            $antibiotics_fifteen      = is_array($antibiotics_fifteen) ? implode(', ', $antibiotics_fifteen) : $antibiotics_fifteen;
            $antibiotics_sixteen      = is_array($antibiotics_sixteen) ? implode(', ', $antibiotics_sixteen) : $antibiotics_sixteen;
            $antibiotics_seven        = is_array($antibiotics_seven) ? implode(', ', $antibiotics_seven) : $antibiotics_seven;
            $antibiotics_eighteen     = is_array($antibiotics_eighteen) ? implode(', ', $antibiotics_eighteen) : $antibiotics_eighteen;
            $antibiotics_nineteen     = is_array($antibiotics_nineteen) ? implode(', ', $antibiotics_nineteen) : $antibiotics_nineteen;
            $antibiotics_twenty       = is_array($antibiotics_twenty) ? implode(', ', $antibiotics_twenty) : $antibiotics_twenty;
            $antibiotics_twenty_one   = is_array($antibiotics_twenty_one) ? implode(', ', $antibiotics_twenty_one) : $antibiotics_twenty_one;
            $antibiotics_twenty_two   = is_array($antibiotics_twenty_two) ? implode(', ', $antibiotics_twenty_two) : $antibiotics_twenty_two;
            $antibiotics_twenty_three = is_array($antibiotics_twenty_three) ? implode(', ', $antibiotics_twenty_three) : $antibiotics_twenty_three;
            $antibiotics_twenty_four  = is_array($antibiotics_twenty_four) ? implode(', ', $antibiotics_twenty_four) : $antibiotics_twenty_four;
            
            try{
                $query = $conn->prepare('UPDATE throat_swab_cs SET patient_id = :patient_id, culture = :culture, bacteria_one = :bacteria_one, bacteria_two = :bacteria_two, bacteria_three = :bacteria_three, antibiotics_one = :antibiotics_one, antibiotics_two = :antibiotics_two, antibiotics_three = :antibiotics_three, antibiotics_four = :antibiotics_four, antibiotics_five = :antibiotics_five, antibiotics_six = :antibiotics_six, antibiotics_seven = :antibiotics_seven, antibiotics_eight = :antibiotics_eight, antibiotics_nine = :antibiotics_nine, antibiotics_ten = :antibiotics_ten, antibiotics_eleven = :antibiotics_eleven, antibiotics_twelve = :antibiotics_twelve, antibiotics_thirteen = :antibiotics_thirteen, antibiotics_fourteen = :antibiotics_fourteen, antibiotics_fifteen = :antibiotics_fifteen, antibiotics_sixteen = :antibiotics_sixteen, antibiotics_seventeen = :antibiotics_seventeen, antibiotics_eighteen = :antibiotics_eighteen, antibiotics_nineteen = :antibiotics_nineteen, antibiotics_twenty = :antibiotics_twenty, antibiotics_twenty_one = :antibiotics_twenty_one, antibiotics_twenty_two = :antibiotics_twenty_two, antibiotics_twenty_three = :antibiotics_twenty_three, antibiotics_twenty_four = :antibiotics_twenty_four, sensitivity_one = :sensitivity_one, sensitivity_two = :sensitivity_two, sensitivity_three = :sensitivity_three, sensitivity_four = :sensitivity_four, sensitivity_five = :sensitivity_five, sensitivity_six = :sensitivity_six, sensitivity_seven = :sensitivity_seven, sensitivity_eight = :sensitivity_eight, sensitivity_nine = :sensitivity_nine, sensitivity_ten = :sensitivity_ten, sensitivity_eleven = :sensitivity_eleven, sensitivity_twelve = :sensitivity_twelve, sensitivity_thirteen = :sensitivity_thirteen, sensitivity_fourteen = :sensitivity_fourteen, sensitivity_fifteen = :sensitivity_fifteen, sensitivity_sixteen = :sensitivity_sixteen, sensitivity_seventeen = :sensitivity_seventeen, sensitivity_eighteen = :sensitivity_eighteen, sensitivity_nineteen = :sensitivity_nineteen, sensitivity_twenty = :sensitivity_twenty, sensitivity_twenty_one = :sensitivity_twenty_one, sensitivity_twenty_two = :sensitivity_twenty_two, sensitivity_twenty_three = :sensitivity_twenty_three, sensitivity_twenty_four = :sensitivity_twenty_four, comments = :comments WHERE id = :id AND patient_id = :patient_id');
                $query->execute([':culture' => $culture, ':bacteria_one' => $bacteria_one, ':bacteria_two' => $bacteria_two, ':bacteria_three' => $bacteria_three, ':antibiotics_one' => $antibiotics_one, ':antibiotics_two' => $antibiotics_two, ':antibiotics_three' => $antibiotics_three, ':antibiotics_four' => $antibiotics_four, ':antibiotics_five' => $antibiotics_five, ':antibiotics_six' => $antibiotics_six, ':antibiotics_seven' => $antibiotics_seven, ':antibiotics_eight' => $antibiotics_eight, ':antibiotics_nine' => $antibiotics_nine, ':antibiotics_ten' => $antibiotics_ten, ':antibiotics_eleven' => $antibiotics_eleven, ':antibiotics_twelve' => $antibiotics_twelve, ':antibiotics_thirteen' => $antibiotics_thirteen, ':antibiotics_fourteen' => $antibiotics_fourteen, ':antibiotics_fifteen' => $antibiotics_fifteen, ':antibiotics_sixteen' => $antibiotics_sixteen, ':antibiotics_seventeen' => $antibiotics_seventeen, ':antibiotics_eighteen' => $antibiotics_eighteen, ':antibiotics_nineteen' => $antibiotics_nineteen, ':antibiotics_twenty' => $antibiotics_twenty, ':antibiotics_twenty_one' => $antibiotics_twenty_one, ':antibiotics_twenty_two' => $antibiotics_twenty_two, ':antibiotics_twenty_three' => $antibiotics_twenty_three, ':antibiotics_twenty_four' => $antibiotics_twenty_four, ':sensitivity_one' => $sensitivity_one, ':sensitivity_two' => $sensitivity_two, ':sensitivity_three' => $sensitivity_three, ':sensitivity_four' => $sensitivity_four, ':sensitivity_five' => $sensitivity_five, ':sensitivity_six' => $sensitivity_six, ':sensitivity_seven' => $sensitivity_seven, ':sensitivity_eight' => $sensitivity_eight, ':sensitivity_nine' => $sensitivity_nine, ':sensitivity_ten' => $sensitivity_ten, ':sensitivity_eleven' => $sensitivity_eleven, ':sensitivity_twelve' => $sensitivity_twelve, ':sensitivity_thirteen' => $sensitivity_thirteen, ':sensitivity_fourteen' => $sensitivity_fourteen, ':sensitivity_fifteen' => $sensitivity_fifteen, ':sensitivity_sixteen' => $sensitivity_sixteen, ':sensitivity_seventeen' => $sensitivity_seventeen, ':sensitivity_eighteen' => $sensitivity_eighteen, ':sensitivity_nineteen' => $sensitivity_nineteen, ':sensitivity_twenty' => $sensitivity_twenty, ':sensitivity_twenty_one' => $sensitivity_twenty_one, ':sensitivity_twenty_two' => $sensitivity_twenty_two, ':sensitivity_twenty_three' => $sensitivity_twenty_three, ':sensitivity_twenty_four' => $sensitivity_twenty_four, ':comments' => $comments, ':patient_id' => $patient_id, ':id' => $id]);

                return true;
            }catch(PDOException $ex){
                return false;
            }
        }

	}