<?php
	require "classes/dashboard.php";

	header('Content-Type: application/json');
	$conn          = $pdo->open();
	$response      = array();

	array_push($response, array(
		"alpha_feto" => Dashboard::get_alpha($conn),
		"antenatal_screening" => Dashboard::antenatal_screening($conn),
		"ascitic_fluid_cs" => Dashboard::ascitic_fluid_cs($conn),
		"aspirate_cs" => Dashboard::aspirate_cs($conn),
		"blood_cs" => Dashboard::blood_cs($conn),
		"blood_film_comment" => Dashboard::blood_film_comment($conn),
		"blood_sugar" => Dashboard::blood_sugar($conn),
		"bue_creatinine" => Dashboard::bue_creatinine($conn),
		"bue_creatinine_egfr" => Dashboard::bue_creatinine_egfr($conn),
		"bue_creatinine_lft" => Dashboard::bue_creatinine_lft($conn),
		"bue_creatinine_lipids" => Dashboard::bue_creatinine_lipids($conn),
		"calcium_profile" => Dashboard::calcium_profile($conn),
		"cardiac_enzyme" => Dashboard::cardiac_enzyme($conn),
		"ca_one_two_five" => Dashboard::ca_one_two_five($conn),
		"ca_one_five_three" => Dashboard::ca_one_five_three($conn),
		"cd4_count" => Dashboard::cd4_count($conn),
		"cea" => Dashboard::cea($conn),
		"ckmb" => Dashboard::ckmb($conn),
		"clotting_profile" => Dashboard::clotting_profile($conn),
		"compact_chemistry" => Dashboard::compact_chemistry($conn),
		"cortisol" => Dashboard::cortisol($conn),
		"crp" => Dashboard::crp($conn),
		"crp_ultra_sensitive" => Dashboard::crp_ultra_sensitive($conn),
		"csf_biochem" => Dashboard::csf_biochem($conn),
		"c_reactive_protein" => Dashboard::c_reactive_protein($conn),
		"d_dimers" => Dashboard::d_dimers($conn),
		"ear_swab_cs" => Dashboard::ear_swab_cs($conn),
		"eye_swab_cs" => Dashboard::eye_swab_cs($conn),
		"endocervical_swab_cs" => Dashboard::endocervical_swab_cs($conn),
		"esr" => Dashboard::esr($conn),
		"estrogen" => Dashboard::estrogen($conn),
		"fbc_3p" => Dashboard::fbc_3p($conn),
		"fbc_5p" => Dashboard::fbc_5p($conn),
		"fbc_children" => Dashboard::fbc_children($conn),
		"folate_b12" => Dashboard::folate_b12($conn),
		"general_chemistry" => Dashboard::general_chemistry($conn),
		"hba1c" => Dashboard::hba1c($conn),
		"hbv_viral_load" => Dashboard::hbv_viral_load($conn),
		"hiv_viral_load" => Dashboard::hiv_viral_load($conn),
		"hepatitis_b_profile" => Dashboard::hepatitis_b_profile($conn),
		"hepatitis_markers" => Dashboard::hepatitis_markers($conn),
		"hormonal_assay" => Dashboard::hormonal_assay($conn),
		"hvs_cs" => Dashboard::hvs_cs($conn),
		"hvs_re" => Dashboard::hvs_re($conn),
		"hypersensitive_cpr" => Dashboard::hypersensitive_cpr($conn),
		"h_pylori_ag" => Dashboard::h_pylori_ag($conn),
		"h_pylori_ag_blood" => Dashboard::h_pylori_ag_blood($conn),
		"h_pylori_ag_sob" => Dashboard::h_pylori_ag_sob($conn),
		"iron_study" => Dashboard::iron_study($conn),
		"ise" => Dashboard::ise($conn),
		"lft" => Dashboard::lft($conn),
		"lipid_profile" => Dashboard::lipid_profile($conn),
		"mantoux" => Dashboard::mantoux($conn),
		"m_alb" => Dashboard::m_alb($conn),
		"ntc_screening" => Dashboard::ntc_screening($conn),
		"pleural_fluid" => Dashboard::pleural_fluid($conn),
		"pregnancy_test" => Dashboard::pregnancy_test($conn),
		"protein_electrophoresis" => Dashboard::protein_electrophoresis($conn),
		"psa" => Dashboard::psa($conn),
		"pth" => Dashboard::pth($conn),
		"pus_fluid" => Dashboard::pus_fluid($conn),
		"reproductive_assay" => Dashboard::reproductive_assay($conn),
		"rheumatology" => Dashboard::rheumatology($conn),
		"sc3_sc4" => Dashboard::sc3_sc4($conn),
		"semen_analysis" => Dashboard::semen_analysis($conn),
		"semen_cs" => Dashboard::semen_cs($conn),
		"serum_hcg_b" => Dashboard::serum_hcg_b($conn),
		"serum_lipase" => Dashboard::serum_lipase($conn),
		"skin_snip" => Dashboard::skin_snip($conn),
		"specials" => Dashboard::specials($conn),
		"sputum_afb" => Dashboard::sputum_afb($conn),
		"sputum" => Dashboard::sputum($conn),
		"stool_cs" => Dashboard::stool_cs($conn),
		"stool_re" => Dashboard::stool_re($conn),
		"tft" => Dashboard::tft($conn),
		"throat_swab_cs" => Dashboard::throat_swab_cs($conn),
		"troponin" => Dashboard::troponin($conn),
		"urethral_cs" => Dashboard::urethral_cs($conn),
		"urine" => Dashboard::urine($conn),
		"urine_acr" => Dashboard::urine_acr($conn),
		"urine_cs" => Dashboard::urine_cs($conn),
		"urine_re" => Dashboard::urine_re($conn),
		"widal" => Dashboard::widal($conn),
		"wound_cs" => Dashboard::wound_cs($conn),
	));

    $pdo->close();
	echo json_encode($response);
?>